# Alternative: App Engine deployment configuration
runtime: python311

entrypoint: python server.py

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  PORT: '8080'
